// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "King Rock",
  domain: "kingrockcannabis.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "1220b King St W, Toronto, ON M6K 1G4",
  streetAddress: "1220b King St W",
  postalCode: "M6K 1G4",
  phone: "(437) 236-3469",
  phoneIntl: "+14372363469",
  neighborhood: "Liberty Village / Parkdale",
  nearbyAreas: ["King St W", "Liberty Village", "Parkdale", "Dufferin", "Exhibition Place", "TTC", "Roncesvalles"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://maps.google.com",
  mapEmbedUrl: "https://maps.google.com/maps?q=King%20Rock%201220b%20King%20St%20W%2C%20Toronto%2C%20ON%20M6K%201G4&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.6395857",
  longitude: "-79.4241844",
  hours: ["Open Daily: 10:00 AM - 01:00 AM"],
  seoTitle: "King Rock | Weed Dispensary in Toronto",
  metaDescription: "King Rock is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["King St W", "Liberty Village", "Parkdale"],
  introVariant: "Welcome to King Rock, your premier weed dispensary in Toronto situated right on 1220b King St W. We are dedicated to providing adults 19+ with top-tier weed, premium cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and CBD products. If you are looking for a trusted cannabis store near Liberty Village / Parkdale or a weed shop near Liberty Village, stop by today to consult with our knowledgeable staff.",
  neighborhoodDescription: "Located in the vibrant Liberty Village / Parkdale district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking is available along King Street West",
  transitNote: "Served by the 504 King streetcar and local TTC transit routes.",
  sectionTitle: "Serving Customers Near Liberty Village in Toronto"
};
