import { STORE_NAP } from "./storeNap";

export const gbpLocation = {
  storeName: STORE_NAP.name,
  domain: STORE_NAP.domain,
  city: STORE_NAP.addressLocality,
  province: STORE_NAP.addressRegion,
  country: STORE_NAP.addressCountry,
  slug: "weed-dispensary-toronto",
  address: STORE_NAP.addressLine,
  streetAddress: STORE_NAP.streetAddress,
  postalCode: STORE_NAP.postalCode,
  phone: STORE_NAP.phoneDisplay,
  phoneIntl: STORE_NAP.phoneIntl,
  neighborhood: STORE_NAP.neighborhood,
  nearbyAreas: [
    "King St W",
    "Liberty Village",
    "Dufferin",
    "Atlantic Avenue",
    "Exhibition Place",
    "Dufferin Gate",
    "TTC 504 King",
  ],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories",
  ],
  menuUrl: "/",
  websiteUrl: STORE_NAP.origin,
  directionsUrl: "/#visit",
  mapEmbedUrl: STORE_NAP.mapEmbedUrl,
  latitude: String(STORE_NAP.latitude),
  longitude: String(STORE_NAP.longitude),
  hours: [STORE_NAP.hoursLabel],
  seoTitle: "King Rock | King West & Liberty Village Cannabis",
  metaDescription:
    "Walk-in cannabis shop at 1220b King St W for King West and Liberty Village. Adults 19+. Open 24 Hours Daily.",
  localLandmarks: ["King St W", "Liberty Village", "Exhibition Place"],
  introVariant:
    "King Rock Cannabis is a neighbourhood walk-in at 1220b King St W on King West, beside Liberty Village and the Exhibition edge. Adults 19+ can browse menu categories including cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and smoking accessories before visiting. The store listing is the homepage.",
  neighborhoodDescription:
    "The storefront faces King Street West at the Dufferin / Atlantic pinch, with Liberty Village north of the rail corridor and Exhibition Place to the south.",
  parkingNote: "Paid street parking on King Street West; Liberty Village Green P when the curb is full",
  transitNote: "Served by the 504 King streetcar, 29/929 Dufferin buses, and the Atlantic Avenue walk from Liberty Village.",
  sectionTitle: "Serving walk-ins on King West and Liberty Village",
};
