export interface SeoPageData { slug:string; title:string; metaDescription:string; h1:string; icon:string; heroTagline:string; banner?:string; sections:{heading:string;body:string}[]; faqs:{q:string;a:string}[]; }
const faqs=[{q:"Where is King Rock?",a:"King Rock is at 1220b King St W in Toronto."},{q:"How can I review the menu?",a:"Use the flower tier and category pages to compare the current public menu before visiting."}];
function page(slug:string,title:string,h1:string,tagline:string,sections:{heading:string;body:string}[]):SeoPageData{return{slug,title,metaDescription:`Plan a King Rock visit on King Street West and browse current menu categories.`,h1,icon:"*",heroTagline:tagline,sections,faqs};}
export const SEO_PAGES:SeoPageData[]=[
page("king-west-weed-dispensary","King West Weed Dispensary | King Rock","King West Weed Dispensary","A King West menu and visit guide",[{heading:"Plan A King West Stop",body:"King Rock is at 1220b King St W near Liberty Village. Review the current category pages before visiting."},{heading:"Browse By Menu Lane",body:"Start with flower tiers or open the pages for pre-rolls, edibles, vapes, concentrates, accessories, and cigarettes."}]),
page("cheap-weed-king-west","Value Weed King West | King Rock","Value Weed Near King West","Compare posted flower tiers and menu prices",[{heading:"Compare The Flower Tiers",body:"Exotic, Premium, AAA+, AA, and Budget are separate menu lanes with posted weights and prices."},{heading:"Confirm Current Details",body:"Use the current tier page or ask staff when one exact item matters."}]),
page("native-cigarettes-king-west","Native Cigarettes King West | King Rock","Native Cigarettes Near King West","Cigarette category and visit information",[{heading:"Browse The Cigarette Category",body:"Use the cigarette menu page to review the current public list before visiting."},{heading:"Confirm Brand Details",body:"Ask staff when a particular brand, package style, or price matters."}]),
page("weed-store-near-liberty-village","Weed Store Near Liberty Village | King Rock","Weed Store Near Liberty Village","Local store information for a King West visit",[{heading:"King Street West Location",body:"King Rock is at 1220b King St W near Liberty Village and Parkdale."},{heading:"Choose A Category First",body:"Use the menu categories to narrow the visit to the product lane you want to compare."}]),
page("dispensary-near-me-king-west","Dispensary Near Me King West | King Rock","Dispensary Near Me In King West","Store details and current menu navigation",[{heading:"Start With Store Details",body:"Check the address and posted hours, then choose a menu category."},{heading:"Use Current Menu Pages",body:"Confirm an exact item through the current menu or with staff."}])];
export function getSeoPageBySlug(slug:string){return SEO_PAGES.find(p=>p.slug===slug);}
