export interface SeoPageData { slug:string; title:string; metaDescription:string; h1:string; icon:string; heroTagline:string; banner?:string; sections:{heading:string;body:string}[]; faqs:{q:string;a:string}[]; }
const faqs=[{q:"Where is King Rock?",a:"King Rock is at 1220b King St W in Toronto."},{q:"How can I review the menu?",a:"Use the flower tier and category pages to compare the current public menu before visiting."}];
function page(slug:string,title:string,h1:string,tagline:string,sections:{heading:string;body:string}[]):SeoPageData{return{slug,title,metaDescription:`Plan a King Rock visit on King Street West and browse current menu categories.`,h1,icon:"*",heroTagline:tagline,sections,faqs};}
export const SEO_PAGES:SeoPageData[]=[
page("king-west-weed-dispensary","King West Weed Dispensary | King Rock","King West Weed Dispensary","Cannabis and smoke-shop shopping on King Street West",[{heading:"Visit King Rock On King Street West",body:"King Rock is at 1220b King St W near Liberty Village."},{heading:"Flower, Edibles, Vapes And More",body:"Compare flower tiers, pre-rolls, edibles, vapes, concentrates, accessories and cigarettes from the listed selection."}]),
page("cheap-weed-king-west","Value Weed King West | King Rock","Value Weed Near King West","Compare posted flower tiers and menu prices",[{heading:"Compare The Flower Tiers",body:"Compare posted weights and prices across Exotic, Premium, AAA+, AA and Budget flower."},{heading:"Confirm Current Details",body:"Check current listings or ask staff when one exact item matters."}]),
page("native-cigarettes-king-west","Native Cigarettes King West | King Rock","Native Cigarettes Near King West","Native cigarette brands and pack styles near King West",[{heading:"Native Cigarette Brands And Prices",body:"Compare the listed cigarette brands, styles and prices from King Rock."},{heading:"King Street West Smoke-Shop Selection",body:"Look for listed full, light and menthol choices near Liberty Village."}]),
page("weed-store-near-liberty-village","Weed Store Near Liberty Village | King Rock","Weed Store Near Liberty Village","Local store information for a King West visit",[{heading:"King Street West Location",body:"King Rock is at 1220b King St W near Liberty Village and Parkdale."},{heading:"Flower, Vapes, Edibles And More",body:"Compare the listed flower tiers, vapes, edibles, pre-rolls, concentrates, accessories and cigarettes."}]),
page("dispensary-near-me-king-west","Dispensary Near Me King West | King Rock","Dispensary Near Me In King West","Store details and current menu navigation",[{heading:"Start With Store Details",body:"Check the address and posted hours, then choose a menu category."},{heading:"Use Current Menu Pages",body:"Confirm an exact item through the current menu or with staff."}]),
page("nicotine-vapes-king-west","Nicotine Vapes King West | King Rock","Nicotine Vapes Near King West","Nicotine vape devices, flavours and prices from King Rock",[{heading:"Nicotine Vape Selection",body:"King Rock lists nicotine vape devices, flavours, formats, puff counts and prices."},{heading:"Compare Devices Near Liberty Village",body:"Review the listed format, flavour, puff count and price before a King Street West visit."},{heading:"Late-Night King West Shopping",body:"Visit King Rock at 1220b King St W during its listed daily hours."}])];
export function getSeoPageBySlug(slug:string){return SEO_PAGES.find(p=>p.slug===slug);}
